# Generated by Django 4.1.3 on 2022-12-22 02:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Tipo Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('num_documento', models.CharField(max_length=16, unique=True, verbose_name='Número de documento')),
                ('nacionalidad', models.CharField(max_length=60, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('num_telefono', models.PositiveIntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de alta')),
                ('legajo', models.PositiveIntegerField(unique=True, verbose_name='Legajo')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatar_empleado', verbose_name='Imagén')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.tipodocumentos', verbose_name='Tipo documento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id'],
            },
        ),
    ]
