# Generated by Django 4.1.3 on 2022-12-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_empleados_num_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenimo'), ('M', 'Masculino'), ('Otro', 'Otro')], default='Otro', max_length=4),
            preserve_default=False,
        ),
    ]
