# Generated by Django 4.1.3 on 2022-12-22 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_empleados_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('GG', 'Gerente General'), ('E', 'Encargado'), ('C', 'Cajero'), ('R', 'Repositor'), ('L', 'Limpieza'), ('V', 'Vendedor')], max_length=60, verbose_name='Tipo de empleado')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
        ),
        migrations.AlterField(
            model_name='tipodocumentos',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='tipo_empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.tipoempleados', verbose_name='Tipo de empleado'),
            preserve_default=False,
        ),
    ]
