# Generated by Django 4.1.3 on 2022-12-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_tipoempleados_alter_tipodocumentos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumentos',
            options={'ordering': ['id'], 'verbose_name': 'TipoDocumento', 'verbose_name_plural': 'TipoDocumentos'},
        ),
        migrations.AlterModelOptions(
            name='tipoempleados',
            options={'ordering': ['id'], 'verbose_name': 'TipoEmpleado', 'verbose_name_plural': 'TipoEmpleados'},
        ),
        migrations.AlterModelTable(
            name='tipodocumentos',
            table='tipo_documentos',
        ),
        migrations.AlterModelTable(
            name='tipoempleados',
            table='tipo_empleados',
        ),
    ]
