# Generated by Django 4.1.3 on 2022-12-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.categorias')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
    ]
