# Generated by Django 4.1.3 on 2022-12-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_clientes_alter_tipodocumentos_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleVenta',
            new_name='DetallesVentas',
        ),
    ]
