# Generated by Django 4.1.3 on 2022-12-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_rename_detalleventa_detallesventas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesventas',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.AlterField(
            model_name='tipodocumentos',
            name='nombre',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('LC', 'Librta Cívica'), ('LR', 'Libreta de Enrolamiento'), ('Pasaporte', 'Pasaporte')], max_length=40, verbose_name='Tipo de documentos'),
        ),
        migrations.AlterField(
            model_name='tipoempleados',
            name='nombre',
            field=models.CharField(choices=[('Gerente General', 'Gerente General'), ('Encargado', 'Encargado'), ('Cajero', 'Cajero'), ('Repositor', 'Repositor'), ('Limpieza', 'Limpieza'), ('Vendedor', 'Vendedor')], max_length=60, verbose_name='Tipo de empleado'),
        ),
    ]
