# Generated by Django 4.1.3 on 2022-12-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_alter_detallesventas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['articulo'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='codigo',
            new_name='articulo',
        ),
    ]
