# Generated by Django 4.1.3 on 2022-12-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='productos',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='productos',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Largo (cm)'),
        ),
    ]
