# Generated by Django 4.1.3 on 2022-12-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_productos_diametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/avatar_empleado', verbose_name='Imagén'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/productos'),
        ),
    ]
