# Generated by Django 4.1.3 on 2022-12-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_alter_empleados_estado_alter_empleados_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='detallesventas',
            table='detalles_ventas',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='ventas',
            table='ventas',
        ),
    ]
