# Generated by Django 4.1.3 on 2023-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_alter_categorias_table_alter_clientes_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='nombre',
        ),
        migrations.AddField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion'),
        ),
    ]
