# Generated by Django 4.1.3 on 2023-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_remove_categorias_nombre_categorias_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
    ]
