# Generated by Django 4.1.3 on 2023-01-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0018_alter_categorias_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
