# Generated by Django 4.1.3 on 2023-01-26 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenimo'), ('M', 'Masculino'), ('Otro', 'Otro')], default='Otro', max_length=4, verbose_name='Género')),
                ('pais', models.CharField(max_length=60, verbose_name='Pais')),
                ('provincia', models.CharField(max_length=60, verbose_name='Provincia')),
                ('localidad', models.CharField(max_length=60, verbose_name='Localidad')),
                ('barrio', models.CharField(max_length=60, verbose_name='Barrio')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('num_telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de alta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('LC', 'Librta Cívica'), ('LR', 'Libreta de Enrolamiento'), ('Pasaporte', 'Pasaporte')], max_length=40, verbose_name='Tipo de documentos')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipo de Documentos',
                'db_table': 'tipo_documentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Gerente General', 'Gerente General'), ('Encargado', 'Encargado'), ('Cajero', 'Cajero'), ('Repositor', 'Repositor'), ('Limpieza', 'Limpieza'), ('Vendedor', 'Vendedor')], max_length=60, verbose_name='Tipo de empleado')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Empleado',
                'verbose_name_plural': 'Tipo de Empleados',
                'db_table': 'tipo_empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColombraroERP.clientes')),
            ],
            options={
                'verbose_name': 'Ventas',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('ancho', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ancho (cm)')),
                ('largo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Largo (cm)')),
                ('alto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alto (cm)')),
                ('volumen', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Volumen (lts)')),
                ('diametro', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Díametro (cm)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColombraroERP.categorias', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['articulo'],
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('num_documento', models.CharField(max_length=16, unique=True, verbose_name='Número de documento')),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=60, verbose_name='Nacionalidad')),
                ('genero', models.CharField(choices=[('F', 'Femenimo'), ('M', 'Masculino'), ('Otro', 'Otro')], max_length=4)),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('num_telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de alta')),
                ('legajo', models.PositiveIntegerField(unique=True, verbose_name='Legajo')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/img/avatar_empleado', verbose_name='Imagén')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColombraroERP.tipodocumentos', verbose_name='Tipo documento')),
                ('tipo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColombraroERP.tipoempleados', verbose_name='Tipo de empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColombraroERP.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColombraroERP.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalles_ventas',
                'ordering': ['id'],
            },
        ),
    ]
