# Generated by Django 4.1.3 on 2023-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0002_clientes_num_documento_clientes_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='barrio',
            field=models.CharField(max_length=30, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=60, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenimo'), ('M', 'Masculino'), ('Otro', 'Otro')], default='Otro', max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='localidad',
            field=models.CharField(max_length=30, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pais',
            field=models.CharField(max_length=30, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='provincia',
            field=models.CharField(max_length=30, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Alto (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Largo (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='volumen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Volumen (lts)'),
        ),
    ]
