# Generated by Django 4.1.3 on 2023-01-27 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0003_alter_categorias_descripcion_alter_categorias_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=25, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='barrio',
            field=models.CharField(max_length=25, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='localidad',
            field=models.CharField(max_length=25, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='num_telefono',
            field=models.IntegerField(max_length=12, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pais',
            field=models.CharField(max_length=25, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='provincia',
            field=models.CharField(max_length=25, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nacionalidad',
            field=models.CharField(max_length=30, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Alto (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='articulo',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='productos',
            name='diametro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Díametro (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Largo (cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='volumen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Volumen (lts)'),
        ),
        migrations.AlterField(
            model_name='tipodocumentos',
            name='nombre',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('LC', 'Librta Cívica'), ('LR', 'Libreta de Enrolamiento'), ('Pasaporte', 'Pasaporte')], max_length=20, verbose_name='Tipo de documentos'),
        ),
        migrations.AlterField(
            model_name='tipoempleados',
            name='descripcion',
            field=models.TextField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipoempleados',
            name='nombre',
            field=models.CharField(choices=[('Gerente General', 'Gerente General'), ('Encargado', 'Encargado'), ('Cajero', 'Cajero'), ('Repositor', 'Repositor'), ('Limpieza', 'Limpieza'), ('Vendedor', 'Vendedor')], max_length=20, verbose_name='Tipo de empleado'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha_compra',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha compra'),
        ),
    ]
