# Generated by Django 4.1.3 on 2023-01-27 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0004_alter_categorias_nombre_alter_clientes_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='num_telefono',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='articulo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
