# Generated by Django 4.1.3 on 2023-01-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0006_alter_clientes_num_telefono_alter_productos_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Alto(cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Ancho(cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='diametro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='Díametro(cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Largo(cm)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='volumen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Volumen(lts)'),
        ),
    ]
