# Generated by Django 4.1.3 on 2023-01-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0007_alter_productos_alto_alter_productos_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='articulo',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Artículo'),
        ),
    ]
