# Generated by Django 4.1.3 on 2023-01-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0008_alter_productos_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='num_telefono',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Imágen'),
        ),
    ]
