# Generated by Django 4.1.3 on 2023-01-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0010_clientes_razon_social_alter_tipodocumentos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo_factura',
            field=models.CharField(choices=[('Factura A', 'Factura A'), ('Factura B', 'Factura B'), ('Factura C', 'Factura C'), ('Factura M', 'Factura M')], default='Factura B', max_length=10, verbose_name='Tipo de factura'),
        ),
    ]
