# Generated by Django 4.1.3 on 2023-01-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0012_rename_tipo_factura_clientes_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='fecha_compra',
            new_name='fecha_venta',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='num_documento',
            field=models.CharField(max_length=16, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pais',
            field=models.CharField(max_length=25, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ColombraroERP.tipodocumentos', verbose_name='Tipo de Documento'),
        ),
    ]
