# Generated by Django 4.1.3 on 2023-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0017_alter_clientes_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
