# Generated by Django 4.1.3 on 2023-02-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0018_productos_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='TipoEmpleados',
        ),
    ]
