# Generated by Django 4.1.3 on 2023-03-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroERP', '0020_alter_productos_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='barrio',
        ),
    ]
