# Generated by Django 4.1.3 on 2023-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColombraroUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Imágen'),
        ),
    ]
